name: docs

on:
  push:	
    branches:	
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build Docs
      run: |
        python ./.scripts/make_docs.py ./X2WOTCCommunityHighlander/Src/ ./X2WOTCCommunityHighlander/Config/ --outdir ./mkdocs
        pip install mkdocs
        cd mkdocs
        mkdocs build -d ../target
    - name: Deploy
      uses: crazy-max/ghaction-github-pages@v1
      with:
        target_branch: gh-pages
        build_dir: target # The folder the action should deploy.
        committer_name: X2CommunityCore-Docs-Bot
      env:
        GITHUB_PAT: ${{ secrets.ACCESS_TOKEN }}